
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import NavbarContainer from './components/NavbarContainer'; 


const inter = Inter({ subsets: ['latin'], variable: "--font-inter" });


export const metadata: Metadata = {
  title: 'Inventory Management ',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <NavbarContainer /> 
        <main className="pt-2">{children}</main>
      </body>
    </html>
  );
}
